DATABASE_URL="postgresql://USER:PASSWORD@HOST.neon.tech/neondb?sslmode=require"
JWT_SECRET="cambia-esto-por-una-clave-larga"

FACTORY_ADMIN_ALIAS="TalentoPyme"
FACTORY_ADMIN_PASSWORD="cambia-esta-clave"
FACTORY_SUPPORT_EMAIL="factory@gmail.com"
FACTORY_ADMIN_ALLOWED_COMPANIES="Mengabo SA,Mengabo Sociedad Anonima"

PAYMENT_PROVIDER="stripe_checkout"
PAYMENT_PROVIDER_API_KEY="sk_live_o_test"
PAYMENT_PROVIDER_PUBLIC_KEY="pk_live_o_test"
PAYMENT_PROVIDER_WEBHOOK_SECRET="whsec_..."
PAYMENT_SUCCESS_URL="https://tu-dominio/factory.html?payment=success"
PAYMENT_CANCEL_URL="https://tu-dominio/factory.html?payment=cancel"
PAYMENT_WEBHOOK_URL="https://tu-dominio/payments/webhook/provider"
PAYMENT_CURRENCY="ARS"
PAYMENT_MODE="production"
APP_BASE_URL="https://tu-dominio"
