import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
const api=fs.readFileSync(new URL('../src/index.js',import.meta.url),'utf8');
const ctx={};vm.createContext(ctx);
vm.runInContext(api.slice(api.indexOf('const ADMIN_COMPANY_CATEGORY_LABELS'),api.indexOf('const adminCompanyCategorySchema'))+';globalThis.f={buildCandidateAdminClassification,candidateQuickFacts,candidateProfessionalSearchText,candidateEvidenceYears,adminSearchTextMatch};',ctx);
const {buildCandidateAdminClassification:classify,candidateQuickFacts:facts,candidateProfessionalSearchText:search,candidateEvidenceYears:years,adminSearchTextMatch:match}=ctx.f;
const candidate=(b={},r={})=>({candidateBolsa:b,resume:r});
test('supermercado no se convierte en instrumentista por especialidad elegida o IA',()=>{
 const c=candidate({ultimoTrabajo:'Despachante de supermercado',especialidad:'Instrumentación',nivel:'Senior',voiceNarrativeSummary:'Instrumentista senior con amplia experiencia en PLC y SCADA'}, {education:'Curso de instrumentación y PLC'});
 const a=classify(c);assert.equal(a.expertiseKey,'COMERCIAL');assert.ok(a.profileScore<=30);assert.equal(match(search(c,a),'instrumentista'),false);
});
test('un senior aislado no acredita experiencia',()=>{const a=classify(candidate({especialidad:'Eléctrica',voiceNarrativeSummary:'Senior gerente jefe experto'}));assert.equal(a.profileScore,null);assert.equal(a.expertiseKey,'GENERAL');});
test('no infiere administración ni primer empleo por falta de datos',()=>{const a=classify(candidate());assert.equal(a.classKey,'INICIAL');assert.equal(a.profileScore,null);});
test('escuela técnica permite orientar pasantía pero no acreditar oficio',()=>{const a=classify(candidate({}, {education:'Escuela técnica, técnico electromecánico'}));assert.match(a.profileTitle,/pasantía técnica/);assert.equal(a.expertiseKey,'GENERAL');assert.equal(a.profileScore,null);});
test('primer empleo explícito es inicial',()=>{const a=classify(candidate({ultimoTrabajo:'Busco mi primer empleo sin experiencia laboral'}));assert.equal(a.classKey,'APRENDIZ');assert.equal(a.profileScore,10);});
test('formación universitaria no prueba cargo profesional',()=>{const a=classify(candidate({nivelEducativo:'Universitaria'},{education:'Estudiante de ingeniería eléctrica'}));assert.equal(a.classKey,'INICIAL');});
test('electricista con trabajo declarado tiene perfil encontrable por término propuesto',()=>{const c=candidate({ultimoTrabajo:'Electricista'},{experience:'2021-2024 Electricista. Reparación de tableros y cableado.'});const a=classify(c);assert.equal(a.expertiseKey,'ELECTRICA');assert.equal(match(search(c,a),'instalaciones mantenimiento'),true);});
test('antigüedad de comercio no infla nivel eléctrico',()=>{const a=classify(candidate({ultimoTrabajo:'Electricista'},{experience:'1995-2025 Cajero de supermercado. 2026-2026 Electricista, cableado y tableros.'}));assert.ok(a.profileScore<45);});
test('mismo texto repetido no mejora calificación',()=>{const line='Electricista, reparación de tableros y cableado';const a=classify(candidate({}, {experience:line}));const b=classify(candidate({}, {experience:Array(20).fill(line).join('\n')}));assert.equal(a.profileScore,b.profileScore);});
test('aspiraciones, negaciones y cursos no atribuyen expertise',()=>{for(const experience of ['Busco trabajar como instrumentista en PLC','Sin experiencia en instrumentación y PLC','No tengo experiencia en PLC','Curso de PLC y SCADA']) assert.equal(classify(candidate({}, {experience})).expertiseKey,'GENERAL',experience);});
test('fecha nacimiento DNI sexo estado civil no modifican calificación',()=>{const base=candidate({ultimoTrabajo:'Electricista'}, {experience:'2010-2025 Electricista. Reparación de tableros.'});const a=classify(base);const b=classify({...base,candidateBolsa:{...base.candidateBolsa,dni:'50111222',fechaNacimiento:'2004-04-04',estadoCivil:'Casado',nacionalidad:'Argentina'}});assert.deepEqual(a,b);});
test('sumatoria laboral no duplica períodos solapados',()=>{assert.equal(years(['2010-2020 Electricista','2015-2025 Electricista']).years,15);});
test('años futuros o invertidos se ignoran',()=>{assert.equal(years(['2040-2050 Electricista']).years,null);assert.equal(years(['2020-2010 Electricista']).years,null);});
test('la edad se calcula con cumpleaños y sin DNI',()=>{assert.equal(facts(candidate({fechaNacimiento:'1986-09-28'}),new Date('2026-09-27')).age,39);assert.equal(facts(candidate({fechaNacimiento:'1986-09-27'}),new Date('2026-09-27')).age,40);assert.equal(facts(candidate({dni:'30111222'})).age,null);});
test('fecha inválida no se convierte en edad',()=>{assert.equal(facts(candidate({fechaNacimiento:'2001-02-30'})).age,null);});
test('contacto extra y ausencias no se inventan',()=>{const f=facts(candidate({telefono:'111',telefonoAdicional:'222',localidad:'ZARATE',estadoCivil:''}));assert.equal(f.additionalPhone,'222');assert.equal(f.city,'Zárate');assert.equal(f.maritalStatus,'');});
test('fecha etiquetada del CV se muestra con procedencia',()=>{const f=facts(candidate({}, {observations:'Fecha de nacimiento: 27/09/1986'}),new Date('2026-09-27'));assert.equal(f.age,40);assert.match(f.ageSource,/CV/);});
test('criterio se recalcula al cambiar el último empleo',()=>{const c=candidate({ultimoTrabajo:'Cajero de supermercado'},{experience:'2010-2015 Electricista, reparación de tableros'});assert.equal(classify(c).expertiseKey,'COMERCIAL');c.candidateBolsa.ultimoTrabajo='Electricista';assert.equal(classify(c).expertiseKey,'ELECTRICA');});
test('teléfono no se filtra por la respuesta resumida de búsqueda',()=>{const block=api.slice(api.indexOf("app.get('/jobs/search'"),api.indexOf("app.get('/jobs/candidate/:id/detail'"));const mapping=block.slice(block.indexOf('.slice(0, 200).map'));assert.doesNotMatch(mapping,/telefono:|quickFacts|evaluacion_profesional:/);});
test('versión 7.10.14 uniforme y campos nuevos opcionales',()=>{const pkg=JSON.parse(fs.readFileSync(new URL('../package.json',import.meta.url)));assert.equal(pkg.version,'7.10.14');const schema=fs.readFileSync(new URL('../prisma/schema.prisma',import.meta.url),'utf8');assert.match(schema,/fechaNacimiento\s+String\?/);assert.match(schema,/telefonoAdicional\s+String\?/);});
test('edad declarada en CV lleva advertencia de vigencia, sin inferencia por DNI',()=>{const f=facts(candidate({}, {observations:'Edad: 45 años'}));assert.equal(f.age,45);assert.match(f.ageSource,/confirmar vigencia/);});
test('ayudante no se convierte en especialista autónomo por años de servicio',()=>{const a=classify(candidate({ultimoTrabajo:'Ayudante electricista'}, {experience:'2000-2025 Ayudante electricista, reparación de tableros y cableado.'}));assert.ok(a.profileScore<=25);assert.match(a.profileTitle,/Auxiliar/);});
